### ISSUE TITLE
build fails as jessie-backports repo was removed from debian ftp

### ISSUE THREAD

**Issue by ramsesrm** [johannestang/bigdata_stack#1]
jessie-backports repo was removed from debian ftp, so the repo needs to replace by this one:

RUN echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" >> /etc/apt/sources.list

see https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository

**Comment by johannestang** [comment]
Thanks for letting me know. I've updated the image to Debian 9 to avoid the issue. It turned out the Hue image was also broken, so I've also updated that, and reorganized the repo to make it more flexible.
